import { useEffect, useState } from 'react';
import { getHistory } from '../api';
import { useNavigate } from 'react-router-dom';

const History = () => {
    const [specs, setSpecs] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const navigate = useNavigate();

    useEffect(() => {
        const fetchHistory = async () => {
            try {
                const data = await getHistory();
                setSpecs(data);
            } catch (error) {
                console.error('Failed to fetch history');
            } finally {
                setLoading(false);
            }
        };
        fetchHistory();
    }, []);

    const formatDate = (dateStr: string) => {
        return new Date(dateStr).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    return (
        <div className="space-y-8">
            <header>
                <h1 className="text-4xl font-extrabold mb-4">Generation <span className="gradient-text">History</span></h1>
                <p className="text-white/60">The last 5 specifications generated by the system.</p>
            </header>

            {loading ? (
                <div className="flex justify-center py-20">
                    <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
                </div>
            ) : specs.length === 0 ? (
                <div className="glass-card p-12 text-center">
                    <p className="text-white/40 text-lg uppercase tracking-widest">No history found</p>
                    <button
                        onClick={() => navigate('/')}
                        className="mt-6 px-6 py-2 bg-primary rounded-full font-bold hover:bg-primary/80 transition-all"
                    >
                        Generate Your First Spec
                    </button>
                </div>
            ) : (
                <div className="grid gap-6">
                    {specs.map((spec) => (
                        <div
                            key={spec._id}
                            className="glass-card p-6 hover:bg-white/5 cursor-pointer transition-all border-l-4 border-l-primary"
                            onClick={() => navigate('/', { state: { initialData: spec } })}
                        >
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="text-xl font-bold text-white mb-1 line-clamp-1">{spec.goal}</h3>
                                    <p className="text-white/40 text-sm">{formatDate(spec.createdAt)}</p>
                                </div>
                                <span className="px-3 py-1 bg-white/10 rounded-full text-xs font-bold text-white/80">
                                    {spec.platform}
                                </span>
                            </div>
                            <div className="grid grid-cols-3 gap-4 text-xs">
                                <div className="flex flex-col">
                                    <span className="text-white/40 uppercase mb-1">User Stories</span>
                                    <span className="text-white font-bold">{spec.userStories.length}</span>
                                </div>
                                <div className="flex flex-col">
                                    <span className="text-white/40 uppercase mb-1">Eng. Tasks</span>
                                    <span className="text-white font-bold">
                                        {spec.engineeringTasks.frontend.length + spec.engineeringTasks.backend.length + spec.engineeringTasks.devops.length}
                                    </span>
                                </div>
                                <div className="flex flex-col text-right">
                                    <span className="text-white/40 uppercase mb-1">View Result</span>
                                    <span className="text-primary">→</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default History;
